// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDle0dBO1S1RjSx6uIThc3wkg_iWmmn78c',
    appId: '1:679815085712:web:d28601f602389062242215',
    messagingSenderId: '679815085712',
    projectId: 'sika-f68e1',
    authDomain: 'sika-f68e1.firebaseapp.com',
    storageBucket: 'sika-f68e1.appspot.com',
    measurementId: 'G-D094MD4EJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzFmZFMgBj_L4vHpg5YmuigdvDuOFMAo4',
    appId: '1:679815085712:android:3be4abe6f484dbde242215',
    messagingSenderId: '679815085712',
    projectId: 'sika-f68e1',
    storageBucket: 'sika-f68e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYATnpI5HdgWVdklfeRleRomNUv8_1OZc',
    appId: '1:679815085712:ios:18fd927c646f3ab4242215',
    messagingSenderId: '679815085712',
    projectId: 'sika-f68e1',
    storageBucket: 'sika-f68e1.appspot.com',
    iosBundleId: 'sika.com.sika',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYATnpI5HdgWVdklfeRleRomNUv8_1OZc',
    appId: '1:679815085712:ios:18fd927c646f3ab4242215',
    messagingSenderId: '679815085712',
    projectId: 'sika-f68e1',
    storageBucket: 'sika-f68e1.appspot.com',
    iosBundleId: 'sika.com.sika',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDle0dBO1S1RjSx6uIThc3wkg_iWmmn78c',
    appId: '1:679815085712:web:533121fa55dfa228242215',
    messagingSenderId: '679815085712',
    projectId: 'sika-f68e1',
    authDomain: 'sika-f68e1.firebaseapp.com',
    storageBucket: 'sika-f68e1.appspot.com',
    measurementId: 'G-VDBSSK5J8H',
  );

}